export const APP_INIT = 'APP_INIT';
export const LOCATION_CHANGE = '@@router/LOCATION_CHANGE';

export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE';

export const USER_SIGNUP = 'USER_SIGNUP';

export const SET_USER = 'SET_USER';

export const LOAD_SEARCH_RESULT = 'LOAD_SEARCH_RESULT';
export const LOAD_SEARCH_RESULT_REQUEST = 'LOAD_SEARCH_RESULT_REQUEST';
export const LOAD_SEARCH_RESULT_SUCCESS = 'LOAD_SEARCH_RESULT_SUCCESS';
export const LOAD_SEARCH_RESULT_FAILURE = 'LOAD_SEARCH_RESULT_FAILURE';

export const LOAD_MOVIE_DETAILS = 'LOAD_MOVIE_DETAILS';
export const LOAD_MOVIE_DETAILS_REQUEST = 'LOAD_MOVIE_DETAILS_REQUEST';
export const LOAD_MOVIE_DETAILS_SUCCESS = 'LOAD_MOVIE_DETAILS_SUCCESS';
export const LOAD_MOVIE_DETAILS_FAILURE = 'LOAD_MOVIE_DETAILS_FAILURE';

export const LOAD_SERIES_DETAILS = 'LOAD_SERIES_DETAILS';
export const LOAD_SERIES_DETAILS_REQUEST = 'LOAD_SERIES_DETAILS_REQUEST';
export const LOAD_SERIES_DETAILS_SUCCESS = 'LOAD_SERIES_DETAILS_SUCCESS';
export const LOAD_SERIES_DETAILS_FAILURE = 'LOAD_SERIES_DETAILS_FAILURE';

export const LOAD_SEASON = 'LOAD_SEASON';
export const LOAD_SEASON_REQUEST = 'LOAD_SEASON_REQUEST';
export const LOAD_SEASON_SUCCESS = 'LOAD_SEASON_SUCCESS';
export const LOAD_SEASON_FAILURE = 'LOAD_SEASON_FAILURE';

export const LOAD_SEASON_COLLECTION = 'LOAD_SEASON_COLLECTION';
export const LOAD_SEASON_COLLECTION_REQUEST = 'LOAD_SEASON_COLLECTION_REQUEST';
export const LOAD_SEASON_COLLECTION_SUCCESS = 'LOAD_SEASON_COLLECTION_SUCCESS';
export const LOAD_SEASON_COLLECTION_FAILURE = 'LOAD_SEASON_COLLECTION_FAILURE';

export const LOAD_USER_SERIES = 'LOAD_USER_SERIES';
export const LOAD_USER_SERIES_REQUEST = 'LOAD_USER_SERIES_REQUEST';
export const LOAD_USER_SERIES_SUCCESS = 'LOAD_USER_SERIES_SUCCESS';
export const LOAD_USER_SERIES_FAILURE = 'LOAD_USER_SERIES_FAILURE';

export const ADD_TO_WATCHLIST = 'ADD_TO_WATCHLIST';
export const ADD_TO_WATCHLIST_REQUEST = 'ADD_TO_WATCHLIST_REQUEST';
export const ADD_TO_WATCHLIST_SUCCESS = 'ADD_TO_WATCHLIST_SUCCESS';
export const ADD_TO_WATCHLIST_FAILURE = 'ADD_TO_WATCHLIST_FAILURE';

export const REMOVE_FROM_WATCHLIST = 'REMOVE_FROM_WATCHLIST';
export const REMOVE_FROM_WATCHLIST_REQUEST = 'REMOVE_FROM_WATCHLIST_REQUEST';
export const REMOVE_FROM_WATCHLIST_SUCCESS = 'REMOVE_FROM_WATCHLIST_SUCCESS';
export const REMOVE_FROM_WATCHLIST_FAILURE = 'REMOVE_FROM_WATCHLIST_FAILURE';

export const ADD_EPISODE = 'ADD_EPISODE';
export const ADD_EPISODE_REQUEST = 'ADD_EPISODE_REQUEST';
export const ADD_EPISODE_SUCCESS = 'ADD_EPISODE_SUCCESS';
export const ADD_EPISODE_FAILURE = 'ADD_EPISODE_FAILURE';

export const REMOVE_EPISODE = 'REMOVE_EPISODE';
export const REMOVE_EPISODE_REQUEST = 'REMOVE_EPISODE_REQUEST';
export const REMOVE_EPISODE_SUCCESS = 'REMOVE_EPISODE_SUCCESS';
export const REMOVE_EPISODE_FAILURE = 'REMOVE_EPISODE_FAILURE';
